### PR TITLE
Add CAP and CAP abilities to their respective files

### PR DESCRIPTION
**Pull request by gamut-was-taken**
Persistent and Rebound weren't added because they don't have an effect on damage.

### CODE REVIEW

**Comment by Rhythms88** [comment]
Next step: removing unviable Pokemon.

**Comment by gamut-was-taken** [comment]
What makes a Pokemon unviable?

**Comment by Rhythms88** [comment]
If it isn't in the viability rankings.

**Comment by gamut-was-taken** [comment]
All right. So only list the Pokemon listed [here][1], right?

  [1]: http://www.smogon.com/forums/threads/cap-viability-ranking-thread-b-rank-filtering.3512508/

**Comment by Rhythms88** [comment]
yeah

**Comment by Rhythms88** [comment]
I'll try to help in a bit

**Pull request merged**
