### PR TITLE
Integrate CAP Viability Rankings into the calculator

### PR DESCRIPTION
**Pull request by gamut-was-taken**
The calculator now only lists the Pokemon that are ranked [here][1], assuming I coded everything right.

But I have to wonder: what if an user wants to use, say, Vaporeon in a damage calculation? Vaporeon isn't ranked but [it's used more than some Pokemon][2] that are ranked.

 [1]: http://www.smogon.com/forums/threads/cap-viability-ranking-thread-b-rank-filtering.3512508/
 [2]: http://www.smogon.com/stats/2015-03/cap-0.txt

Note to self: alphabetize the properties in pokedex.js

### CODE REVIEW

**Comment by Rhythms88** [comment]
Hmm, with some Pokemon that are used a lot but aren't on the viability rankings, we can give them a special rank like 'H' for High Use

**Comment by gamut-was-taken** [comment]
What should be considered "used a lot?" 

On a somewhat side note, I think it's strange that Pokemon like Vaporeon and Lucario aren't ranked but are used more than Pokemon like Regice, which is ranked C-.

**Comment by Rhythms88** [comment]
I would say 3.41% or higher usage in cap 1500

**Comment by gamut-was-taken** [comment]
No unranked Pokemon in the last three months has 3.41% usage or over in CAP-1500. That said I'm fine with whatever you're fine with.

**Comment by gamut-was-taken** [comment]
Next is sets, I assume?

[Only a couple of Pokemon have completed sets](http://www.smogon.com/forums/threads/cap-metagame-analysis-reservation-index-read-carefully.3525839/). The rest are in the process of having sets written up or not.

What do you want to do for the last two cases?

**Comment by Rhythms88** [comment]
Hmm, i dont know tbh

**Comment by gamut-was-taken** [comment]
What do you think of these general guidelines for sets?

* Prefer CAP sets for Pokemon that have them, otherwise...
* Prefer OU sets for Pokemon that have them, otherwise...
* Build a "Showdown Common" set from the monthly CAP-1500 data

Also, what do you think about including Pokemon that have more than 0.56654% usage? The 3.41% cutoff was an attempt to cap OU at 50 Pokemon. 0.56654% is the percent I heavily approximated that would raise the cap to 100 Pokemon.

**Comment by Rhythms88** [comment]
YEah that's fine

**Pull request merged**
